import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Header, Cart, List, DefaultButton } from '../components';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Cart
            open={false}
        />
        <List 
            content={[]}
        />
        <div>
            <DefaultButton 
                label="Carregar mais"
            />
        </div>
      </main>
    </div>
  )
}
